### ISSUE TITLE
Vertical Scroll with Horizontal Swipe

### ISSUE THREAD

**Issue by missashmarie7** [mattbryson/TouchSwipe-Jquery-Plugin#101]
Hello,

I'm using this plugin to swipe between pages and I also need a vertical scroll so users can see more information below the viewport. After changing "allowPageScroll" to "vertical" per the instructions on this page: http://labs.rampinteractive.co.uk/touchSwipe/demos/Page_scrolling.html I was able to accomplish what I wanted EXCEPT, if you scroll down the page vertically before you swipe horizontally (which would be the likely behaviour of users), you can't go back and swipe horizontally. I noticed there is a note on the link above that says "Note how the vertical swipe is hit and miss. As soon as the page starts scrolling, the user is no longer swiping across the object." - does this mean that I won't be able to get the horizontal swipe to work after the vertical scroll??? Any help would be much appreciated!!!!!

**Comment by michaelkoehne** [comment]
And same problem here.
