### ISSUE TITLE
Disable swipe completely on up and down but work only in left and right for document

### ISSUE THREAD

**Issue by ghost** [mattbryson/TouchSwipe-Jquery-Plugin#109]
I am new to touchswipe plugin.

I have an issue which in the usage of the touchswipe plugin.

I have a responsive page with a menu which slides from right to left. This should happen on swipeLeft and close on swipeRight.

However I have an issue. While implementing the swipe on the document, I want the touchswipe script to be active only when swipe left and right. In up and down it should be disabled.

The reason being the script, governs the up and down  page scroll and that makes the page very slow while scrolling in slower mobile javascript engines.

I would like to be able to use the swipe on document and it should only be enabled for right and left and disabled for up and down so that the default page scroll works and not the script forced one.

**Comment by EnzoIntiso** [comment]
> Not to sure how that helps. If pageScroll is 'auto' (the default) then assigning a swipeLeft handler will capture ONLY swipe left events. All other swipes events will propagate up and trigger a native page scroll.

It's still buggy on iOS 9.3.2 as, even if with pagescroll 'auto' and only swipeLeft and swipeRight assigned, vertical scrolling is faulty (sometimes works sometimes not). It seems that swipeUp and swipeDown are caught anyway even if don't assigned preventing scrolling.

**Comment by saturday1** [comment]
Would be really grateful if somebody could help me out with this script/bug! I tried with `preventDefaultEvents: false`, but it is just blocking all swipes, including left and right.

    jQuery(".sy-wrapper li").swipe( {
		tap: function() {
			var link = jQuery(this).find('a').attr('href');
			if (link) window.location.href = link;
		},
		// Swipe left
		swipeLeft: function(){
			jQuery(".sy-wrapper li a").click(function(event) {
				event.preventDefault();
			});
			thumbs.goToPrevSlide();
			// Check if paused - stay paused
			if(jQuery('.sy-controls').hasClass('is-paused')){
				setTimeout(function(){
					thumbs.stopAuto();
				}, transitionTime + addOnTime);
			}
		},
		// Swipe right
		swipeRight: function(){
			jQuery(".sy-wrapper li a").click(function(event) {
				event.preventDefault();
			});
			thumbs.goToNextSlide();
			// Check if paused - stay paused
			if(jQuery('.sy-controls').hasClass('is-paused')){
				setTimeout(function(){
					thumbs.stopAuto();
				}, transitionTime + addOnTime);
			}
		}, 
		allowPageScroll:"vertical",
		preventDefaultEvents: false,
		excludedElements: ".noSwipe"
	});
