### ISSUE TITLE
Swipe should "capture " the mouse, i.e. listen to mousemove events on the window?

### ISSUE THREAD

**Issue by Ziriax** [mattbryson/TouchSwipe-Jquery-Plugin#128]
Once swiping starts, mousemove and mouseup events should be observed on the window, not the element itself.

Otherwise you cannot "drag" small DIV elements: as soon as the mouse leaves the DIV element, swiping breaks.

http://jsfiddle.net/ydqvJ/5/

Grab the red DIV, and quickly move the mouse. 

Even if the red DIV is not moved, swiping seems to stop when the mouse leaves the element.

**Comment by Ziriax** [comment]
Could you maybe explain a bit why this issue was closed? Thanks

**Comment by mattbryson** [comment]
Sorry, I was clearing out a list of old and no longer relevant tickets so
we can focus on the main issues, and forgot to update this one.

The plugin already supports maintaing the swipe when the user leaves the
target element, im not sure if this was the case when you raised the issue.

The swipe event is not completed / cancelled until the user releases, or
reaches any of the thresholds that might be set.

For the swipe event to be cancelled when the user leaves the element you
can set the options 'triggerOnTouchEnd' and 'triggerOnTouchLeave'. See
http://labs.rampinteractive.co.uk/touchSwipe/demos/Trigger_handlers.html

Also, this plugin isn't really suited for dragging, something like JQ
draggable would be more appropriate.  It's more concerned with movement
across elements.  If you need to position an element, you may have more
luck having the swipe handler on a parent, and updating the child position
on swipe.


Cheers


Matt


M
