### ISSUE TITLE
One-finger AND two-finger swipes on same DOM element

### ISSUE THREAD

**Issue by wutmikee** [mattbryson/TouchSwipe-Jquery-Plugin#143]
I (along with others) have been trying to figure out how to run functions on the same DOM node with separate options for both one-finger and two-finger swipes. Please see StackOverflow thread here:

http://stackoverflow.com/questions/19987462/multi-finger-touch-swipe-event

**Comment by rexcalibur** [comment]
hi, i have a problem with swipeDown using 4 fingers, it didn't work. :(

    $('#test')swipe({
      pinchIn: function() {
        //zoomIn
      },
      pinchOut: function() {
        //zoomOut
      },
      swipeDown: function(event, direction, distance, duration, fingerCount, fingerData) {
        if (fingerCount === 2) {
          //drag down
        } else if (fingerCount === 4) {
          //do something
        }
      },
      swipeUp: function(event, direction, distance, duration, fingerCount, zoom, fingerData) {
        if (fingerCount === 2) {
          //drag up
        }
      },
      threshold:50,
      fingers:'all',
      pinchThreshold:50
    });
