### ISSUE TITLE
Testing TouchSwipe

### ISSUE THREAD

**Issue by bob-fornal** [mattbryson/TouchSwipe-Jquery-Plugin#147]
I am developing a touch-enabled page for use on an iPOD.  I am using TouchSwipe for user actions ... and it is working amazingly well.

My issue is in developing qUnit tests to test the TouchSwipe behaviors.

What I need to be able to do is fire the touch events via code to see that the code fires correctly.

Here's the code I am using to capture a swipeLeft and tap ...

<pre>
var self = this;

self.__object.swipe({
    excludedElements: "button, input, select, textarea, .noSwipe",
    swipeLeft:function(event, direction, distance, duration, fingerCount) {
        console.log(event);
        // TRACK ORDER INFORMATION
        if (self._Handler._okToClick) {
            // TRUE/FALSE STATE RECORDED IN OrderID;
            //            MATCHES ORDERS IN OrderLIST
            self._cacheDOM();
            self._Handler._Jugs._uncacheDOM();
            self._Handler.internalNavigate(self._nextObject, "");
            setTimeout(function() {
                self._Handler._okToClick = true;
            }, 20);
        }
    },
    tap: function(event, target) {
        console.log(event);
        self._Handler.process_tap_Switches(target, "order");
    }
});
</pre>

How can I fire the swipeLeft and tap (via code) so the internal functions are executed?

I have read in the documentation that this is doable, but cannot find any examples or documentation on how to do this for my unit tests.

**Comment by tkhelifiT** [comment]
Could you tell us more about how to define swipeHandler ?
Thank you!

**Comment by mattbryson** [comment]
$('#swipe_element").on('swipe', function(event, direction, distance, duration, fingerCount) {
    console.log(event);
})
