### ISSUE TITLE
Anchors interaction issue

### ISSUE THREAD

**Issue by LoomyBear** [mattbryson/TouchSwipe-Jquery-Plugin#153]
I've had a problem of touchSwipe.js not triggering swipe events over a elements. I've made my research and found the answer pretty quickly. I had to exclude **a** from the excluded elements.

This solution worked very well apart from the fact that anchors stopped to behave like they are supposed to behave ... like open web pages for example, or trigger click events when processed by JS.

I found a half-measure solution for opening URL links, which is checking for **tap** events on an element and if this element has **href** I *window.open* it. But what should I do if I want to process clicks with javascript, AJAX form submit for example? Should I use **tap** event again? I really don't want to process all the clicks on anchors through *tap: { function(){ blah; } }*.

Is there any way to do something like:
*tap: function(){ if ( target.is("a") ) { stopSwipePropogation() or doAsUsual(); } }*

So after this the following structure will work as expected:
*$("a").on({ click: function(){ doStuff(); } })* <-- right now it doesn't

I guess I'm missing something really important here. Can anyone clarify please? Thanks!

**Comment by lkrids** [comment]
+1

**Comment by mattbryson** [comment]
This should be fixed in master now, will do a build soon with it in.  Tapping an element without moving will allow its events to bubble up normally.  swiping from this element will not and trigger a swipe.
