### ISSUE TITLE
excludedElements:[] > Block normal href on android

### ISSUE THREAD

**Issue by Sebguy1** [mattbryson/TouchSwipe-Jquery-Plugin#159]
Hi!
I am using a slider with big images surrounded by a link and need to use excludedElements:[] to make the swipe trigger.

The problem is when I add this property, the link fail to load when clicked (not swiped) on android devices (currently tested on chrome for nexus 5). This is bad because i need theses links to work (and my slider to swipe).

There is a bit more code information:
$('#slider .slides_box').swipe({
		swipe:function(event, direction, distance, duration, fingerCount) {
			if($('#slider .slides_box a.slide').is(":animated") == false && (direction == 'left' || direction == 'right')){
				myFunction(direction);
			}
		},
		threshold:0,
		excludedElements:[]
	});

This work for my ipad touch 2nd generation, and firefox on my PC.
My customer will test his mobile version on a android.

Do you have any idea on how to fix this?

I tryed to get my link replaced with a div and trigger an onlick javascript event, still dont work.

Thanks a lot!

**Comment by mattbryson** [comment]
Will raise a new feature request for allowing taps through if not swipe occured
