### ISSUE TITLE
Swipe and Pinch together

### ISSUE THREAD

**Issue by plutov** [mattbryson/TouchSwipe-Jquery-Plugin#160]
Separately, swipe and pinch work good. But now I want to swipe elements and also need a possibility to pinch.

    el.swipe({
        triggerOnTouchEnd: true,
        swipeStatus: function(event, phase, direction, distance) {

        },
        doubleTap: function() {

        },
        tap: function() {

        },
        maxTimeThreshold: 250,
        pinchStatus: function(event, phase, direction, distance , duration , fingerCount, pinchZoom) {

        },
        pinchThreshold: 0,
        allowPageScroll: 'vertical'
    });

But pinchStatus function is never triggering. How can theirs work together?

**Comment by mattbryson** [comment]
This is fixed in 1.6.8 59e13867707fb559799eca6c70ba073bc3d46a91
