### ISSUE TITLE
Button click event doesn't seem to work

### ISSUE THREAD

**Issue by Davecameron77** [mattbryson/TouchSwipe-Jquery-Plugin#163]
Just a learner at this sort of thing, but some interesting things with the button tag.

Tap event doesn't work, and doesn't appear to be replacing the click event.

Example here.
http://jsfiddle.net/CkEgW/

**Comment by mattbryson** [comment]
As of 1.6.15 All inputs now bubble events if the user does not swipe over them.  So taps, button press will bubble up and fire as per normal, unless the user swiped over them.
