### ISSUE TITLE
Chrome Android: Swipe on element opacity 0

### ISSUE THREAD

**Issue by ardok** [mattbryson/TouchSwipe-Jquery-Plugin#165]
I think Google Chrome team needs to handle this?
It seems that it works just fine on Safari, mobile Safari, desktop Chrome, and Android Dolphin Browser.

The only time it would work is when I do remote debugging, go to `Elements` tab, and hover my mouse on any DOM element there, then `swipe` listener (including `tap`) will work. Otherwise, it won't work.

Tested on:
Chrome Beta 34.0.1847.76
Chrome 33.0.1750.166

Just thought I throw it out there in case someone else runs into the same problem.
I'm basically using an overlay over some image so users can slide through them.
The overlay has `position:absolute;top:0;bottom:0;left:0;right:0;`. That's not enough apparently. Need to set some kind of `opacity`. I put `opacity:0` and it didn't work.
After some time, I finally figured out that the problem was the opacity. As long as the opacity value `!= 0`, you're good.

**Comment by mattbryson** [comment]
Yeah, not sure that we can do much about this.
