### ISSUE TITLE
allowpagescroll = "vertical" stopped the functioning of swipeup and swipedown.

### ISSUE THREAD

**Issue by anupamsingh31** [mattbryson/TouchSwipe-Jquery-Plugin#175]
I have a requirement in which there is swipe up (to load next record )and swipe down(to load previous record )functionality needed. Sometimes the record shown makes the page  scroll able vertically. Its not a problem in large screen devices in which there is no scroll but in small screen devices where we have to scroll down to see the whole record  the record is not scroll able at all. I put ' allowedpagescroll = "vertical" ' but it only allows swipe Left and swipe Right.
How do i get both the vertical scrolling and swipe up & down on the page to work together.

**Comment by amelia949** [comment]
Date: Tue, 9 Sep 2014 03:04:13 -0700
