### ISSUE TITLE
text selection area and action menu doesnot goes off after swipe

### ISSUE THREAD

**Issue by pratikt-cuelogic** [mattbryson/TouchSwipe-Jquery-Plugin#176]
text selection area and action menu doesnot goes off after swipe, swipe effect is blocking default behaviour

**Comment by mattbryson** [comment]
You can enable / disable the prevention of default events, this might help.

http://labs.rampinteractive.co.uk/touchSwipe/docs/symbols/%24.fn.swipe.defaults.html#preventDefaultEvents
