### ISSUE TITLE
How to ignore swipe up/down

### ISSUE THREAD

**Issue by victorjavierss** [mattbryson/TouchSwipe-Jquery-Plugin#182]
Is there an option to disable the swipe up/down detection for letting the browser to continue scrolling if I want only swipe to the left and to the right?

**Comment by hurycz** [comment]
not working on iphone5 chrome/safari, still swipe (up/down) and no scrolling

**Comment by miguelmich** [comment]
I'm having the same issue on iPhone 5, but it only happens when I set `swipeLeft` option.

**Comment by mattbryson** [comment]
fixed in latest release
