### ISSUE TITLE
Window Phone support

### ISSUE THREAD

**Issue by acwolff** [mattbryson/TouchSwipe-Jquery-Plugin#183]
The latest version of the Windows Phone is not supported by the TouchSwipe plug-in. When can we expect support for that smartphone?

**Comment by stevenliemberg** [comment]
+1

**Comment by mattbryson** [comment]
Ill have a look into this later today

**Comment by mattbryson** [comment]
Have issues, my windows phone emulator doesn't appear to report anything for window.navigator.msPointerEnabled, window.navigator.pointerEnabled or Window.PointerEvent.

Will have to wait to Tuesday when I can get my hands on an actual device.

**Comment by raulsouzalima** [comment]
+1

**Comment by flexphperia** [comment]
+1

**Comment by glat** [comment]
+1

**Comment by rspahni** [comment]
See here for the fix: #218

**Comment by mattbryson** [comment]
fixed in latest release
