### ISSUE TITLE
Pinch And Swipe not working toghether

### ISSUE THREAD

**Issue by drpain** [mattbryson/TouchSwipe-Jquery-Plugin#192]
I have been playing with the plugin and out of all the ones out there I like this one the most. The others are either over complicated or not as advertised. 

The only issue I have is that I am trying to create a single "Swipe" and "Pinch" area, but they example as I found on http://labs.rampinteractive.co.uk/touchSwipe/demos/Pinch_and_Swipe.html doesn't seem to work.

It is only detecting swipes and not pinches at all. Anyone have some idea of a workaround?

**Comment by mattbryson** [comment]
This is fixed in 1.6.8 59e13867707fb559799eca6c70ba073bc3d46a91

**Comment by henviale** [comment]
I've just verified that with version 1.6.14 it is still not working.
Tested on iPad Mini within a Phonegap application.

Is it possible to reopen the issue ?
can anyone provide a workaround for this ?
