### ISSUE TITLE
Windows Phone Bugs

### ISSUE THREAD

**Issue by Lostbrokenkey** [mattbryson/TouchSwipe-Jquery-Plugin#198]
Hi Matt,

i get continuously the same issues, could it be bugs in the plugin?

1)
Browser:
Mozilla/5.0 (Mobile; Windows Phone 8.1; Android 4.0; ARM; Trident/7.0; Touch; rv:11.0; IEMobile/11.0; NOKIA; Lumia 830) like iPhone OS 7_0_3 Mac OS X AppleWebKit/537 (KHTML, like Gecko) Mobile Safari/537

jquery.touchSwipe.js on Line 551
EXCEPTION Unable to get property '0' of undefined or null reference 

2)
Browser:
Mozilla/5.0 (iPhone; CPU iPhone OS 8_0 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0 Mobile/12A365 Safari/600.1.4

jquery.touchSwipe.js on Line 1596
EXCEPTION TypeError: undefined is not an object (evaluating 'f.end') 

greez

**Comment by safonovilya** [comment]
Hi Matt!

I have the same problem on current project. 
Is there a chance what issue will been solved it in the near future?

Thanks

**Comment by mattbryson** [comment]
Yup, definite issues with the ms pointer events, I will look at it, just don't have much time at the moment..

**Comment by larsoneric** [comment]
I'm looking forward to a fix for TypeError: 'undefined' is not an object (evaluating 'f.end'). I get this error a couple hundred times a day.

**Comment by rspahni** [comment]
+1

**Comment by rspahni** [comment]
See here for the fix: https://github.com/mattbryson/TouchSwipe-Jquery-Plugin/issues/218

**Comment by filfat** [comment]
+1
