### ISSUE TITLE
Rund the function again after changing DOM (with SwipeStatus)

### ISSUE THREAD

**Issue by Marc3llo** [mattbryson/TouchSwipe-Jquery-Plugin#201]
Hey, this is a very useful plugin and I use it for many projects. However I'm having an issue, since I shuffle some DOM elements, obviously they are new to the DOM when shuffling is done, so I recall the swipe Function, this seems to work when I use a simple swipe, as the jsfiddle here http://jsfiddle.net/4CLqY/21/ (not my fiddle) shows. However, if I use swipeStatus to do more complex things, I seem not to be able to call it again. After the new elements are loaded and I call the function again, all that happens is that console.log shows me 0 distance and no direction, and that only once, then it doesn't outupt anything anymore. Any clue how to fix this?

I found out, that I can call the function again within new elements, let's say if I have a swipe() on .div and I recall after removing and replacing .div, nothing habens, however if I do the same and call a new swipe() on, let's say .p widthing .div, it works, but just once.

Any ideas? might it be, because i replace all elements?

**Comment by kevjvek** [comment]
Yes, replacing the elements causes problems with any event handlers. I've found that simply registering handlers again after adding new elements if unreliable. When I'm doing significant DOM rejiggering I usually write a function that unregisters *all* event handlers and then reregisters them to ensure that handlers work properly for all current DOM elements. I call this function every time DOM elements change to ensure properly registered event handlers.
