### ISSUE TITLE
disable image swipe at end

### ISSUE THREAD

**Issue by nevoeiro** [mattbryson/TouchSwipe-Jquery-Plugin#203]
Hi there,

Thanks for the great plugin! I'm testing it for a digital book for iPad.
I would like to disable image right swipe if i'm in first image and image left swipe if i'm in last image of gallery.
The idea is turn the page of book in these cases.
What is the best way to get this working?

Thanks, all the best!
cb

**Comment by kevjvek** [comment]
This is a bit old now, but...
If you're using jquery you can check for .next() and .prev() from the current page.
if(swipedir = left){
    var next = currentpage.next()
    if(next.length > 0){
        //swipe left handler
    }
} else if(swipedir = right) {
    var prev = currentpage.prev()
    if(prev.length > 0){
        //swipe right handler
    }
}
