### ISSUE TITLE
memory leak after destroy method called

### ISSUE THREAD

**Issue by flexphperia** [mattbryson/TouchSwipe-Jquery-Plugin#206]
I've found memory leak after destroy method is called, without below fix Chrome developer tools shows reference to $element object after its removed from DOM

```
this.destroy = function () {
   removeListeners();
   $element.data(PLUGIN_NS, null);
   $element = null; //new line
   //deleted line
};
```

**Comment by mattbryson** [comment]
Good spot - ill add this to the next build.
