### ISSUE TITLE
differentiate between swipe and drag

### ISSUE THREAD

**Issue by mourdeveloper** [mattbryson/TouchSwipe-Jquery-Plugin#207]
i have page where i have both swipe and drag .

Now i see when i drag swipe also comes into action , how can i solve this issue

**Comment by mattbryson** [comment]
You can disable swiping on non touch devices with the options object (this is in the docs, but not the demos)

options.fallbackToMouseEvents=false;

See http://labs.rampinteractive.co.uk/touchSwipe/docs/symbols/%24.fn.swipe.defaults.html for the options arguments, but basically you would init swipe like this...

```javascript
$(function() {      
    $("#test").swipe( {
        swipe:function(event, direction, distance, duration, fingerCount, fingerData) {
          $(this).text("You swiped " + direction );  
        },
        fallbackToMouseEvents:false
      });
    });
```
