### ISSUE TITLE
Tap event should not fire if a user scrolls before releasing finger.

### ISSUE THREAD

**Issue by raldred** [mattbryson/TouchSwipe-Jquery-Plugin#209]
Imagine i'm a user on a large page.
There's a button/action with a swipe tap event handler.
If I touch that button as my starting point to scrolling the page, the `tap` event on the button/action will be triggered when I let go.
When you scroll the page "sticks" to your finger so you'll often trigger `touchstart` and `touchend` at the same co-ordinates. 

This [Demo](http://jsbin.com/tetafi) illustrates the issue, use red button as your the scroll anchor.

This is incorrect behaviour, the `tap` event should be cancelled if actually scrolling the page.

The only way I can think of reliably detecting this is checking the `event.cancelable` boolean.
This will be false if the `touchend` event was triggered after scrolling.

I have tried this in the event callbacks and it seems to work reliably.
Anyone else got any suggestions?

It feels like we need a `cancelTapOnScroll` option

**Comment by lukatiks** [comment]
Unfortunately it looks like my Firefox for Android 36.0.4 does not set `event.cancelable` to `false` on `touchend` after scrolling so some other scroll detection method would be needed for it.

Firefox seems to send `scroll` events when scrolling, maybe they can be used?

**Comment by djalfe** [comment]
@mattbryson Was a solution for this ever created? I've been struggling with the same issue for a few hours today until i saw this issue and was able to "hack" it by doing the following in the top of my event handler, but i feel it should be taken care of by the plugin

```
if (!e.cancelable) { // the page was scrolled
   return false;
}
```

**Comment by mattbryson** [comment]
Hmm, it shouldn't be doing that as there is a distance threshold used by
the tap detection, if the pointer moves beyond that, it's not a tap. Will
have a butchers in the morning....

**Comment by jamiehumphries** [comment]
I have also found this issue today when testing on iOS with TouchSwipe v1.6.18.

Is there any news on a fix?

**Comment by raldred** [comment]
This was never resolved. 
@mattbryson the pointer doesn't move beyond the threshold, the content on the page doesn't move relative to the viewport because it's scrolling. It needs to take into account page offset. The demo I created 2 years ago still shows the issue.
