### ISSUE TITLE
Cannot select text on non-mobile device

### ISSUE THREAD

**Issue by akjackson1** [mattbryson/TouchSwipe-Jquery-Plugin#210]
I'm facing a problem where text cannot be selected when applying a swipe event to the entire page.
Is there a solution to this? Or a way to disable TouchSwipe in non-mobile devices?

**Comment by mattbryson** [comment]
You can disable child elements from triggering the swipe event, so you can exclude you text areas / certain divs from triggering the swipe which would then allow text selection.

http://labs.rampinteractive.co.uk/touchSwipe/demos/Excluded_children.html

OR, you can disable swiping on non touch devices (not non-mobile, but non touch).

options.fallbackToMouseEvents=false;

See http://labs.rampinteractive.co.uk/touchSwipe/docs/symbols/%24.fn.swipe.defaults.html for the options arguments, but basically you would init swipe like this...

```javascript
$(function() {      
    $("#test").swipe( {
        swipe:function(event, direction, distance, duration, fingerCount, fingerData) {
          $(this).text("You swiped " + direction );  
        },
        fallbackToMouseEvents:false
      });
    });
```

**Comment by spenat28** [comment]
It dooes not seems to solve this issue for me

```javascript
$(document)
    .swipe({
        swipeLeft: function (event, direction, distance, duration, fingerCount, fingerData) {
            dummy();
        },
        swipeRight: function (event, direction, distance, duration, fingerCount, fingerData) {
            dummy();
        },
        threshold: 250,
        preventDefaultEvents: false, // this should work?
        fallbackToMouseEvents: false // or this one ... but neither
    });
```
