### ISSUE TITLE
TouchSwipe clashes with Jquery UI tab

### ISSUE THREAD

**Issue by nsylmz** [mattbryson/TouchSwipe-Jquery-Plugin#212]
I am trying to implement a responsive tab with using touchswipe and jquery ui tab. However the swipe isn't working with jquery ui tab. I implemented in Jsfiddle http://jsfiddle.net/xym6wbnz/

**Comment by mattbryson** [comment]
Not too sure what your trying to achieve - touch swipe appears to be applied to the tab bar?  But that already has its own click events that are probably overriding it?

What are you trying to do in terms of user interaction?
