### ISSUE TITLE
Suggestion: add simple step setup

### ISSUE THREAD

**Issue by pyk** [mattbryson/TouchSwipe-Jquery-Plugin#213]
correct me if I'm wrong, but I don't see anything related on how to use this libs on my current project.

You have done a good job to build this libs and I think when you include simple step on how to use this in [README](https://github.com/mattbryson/TouchSwipe-Jquery-Plugin/blob/master/README.md) and [Homepage](http://labs.rampinteractive.co.uk/touchSwipe/demos/) it will be more useful. 

For example a quick simple installation setup using bower

```
bower install jquery-touchswipe --save
```

**Comment by mattbryson** [comment]
added to master read me, will tag once windows changes are in.
