### ISSUE TITLE
[Q]How to capture pinch distance without breaking scroll and pinch?

### ISSUE THREAD

**Issue by Joshua-Interspace** [mattbryson/TouchSwipe-Jquery-Plugin#214]
$(document).swipe( {
    pinchStatus:function(event, phase, direction, distance , duration , fingerCount,pinchZoom) {
        console.log("Distance pinched "+distance+" , Direction " + direction);
    },
        preventDefaultEvents: false,
        fingers:2,
        pinchThreshold:1,
        triggerOnTouchEnd: true
});
This captures the pinch as i want but wont let the page zoom or scroll.

**Comment by mattbryson** [comment]
At the moment pinch will capture the event, and there is no option to allow it through.

Ill have a look to see if its a quick fix.

m

-- 
Matt Bryson


On 2 February 2015 at 10:20:57, Joshua-Interspace (notifications@github.com) wrote:

$(document).swipe( {
pinchStatus:function(event, phase, direction, distance , duration , fingerCount,pinchZoom) {
console.log("Distance pinched "+distance+" , Direction " + direction);
},
preventDefaultEvents: false,
fingers:2,
pinchThreshold:1,
triggerOnTouchEnd: true
});
This captures the pinch as i want but wont let the page zoom or scroll.

**Comment by Joshua-Interspace** [comment]
$.trigger(event); after the console.log will let the event continue but it gives me a lot of JS error instead and the console.log stops loging the right information.

**Comment by mattbryson** [comment]
Where did you see the 'preventDefaultEvents' option ?  Cant find that in the library.  But I certainly can add one in, so you can force it to still bubble up and trigger the browser default behaviour ?

**Comment by Joshua-Interspace** [comment]
http://buildbetteronline.com/?p=99 i think, i searched the net for like 2 days for a way to get it to pass through the events, not sure where he got that option from then, hehe.

that would be lovely, just what i want it to do, i just wanna hook on the pinch, extract the data and still let the pinch happen.

**Comment by mattbryson** [comment]
Ive just pushed a new branch with this in (allow_default_events).  12104648e492c35d7a8e144147862c2c8573e386  

Not had time to test it, so it may not help - but that will honor the preventDefaultEvents setting, and run the pinch AND trigger the default event.

Give it a bash - if it works ill merge it into master.

**Comment by Joshua-Interspace** [comment]
replaced my touchswipe.min.js with the new one and tried a minimal approach but didnt work, it will still log the numbers but not let me scroll (move) or pinch, im using an Nexus 5 with latest Chrome for android if it makes any diff:

        $(document).swipe( {
	        pinchStatus:function(event, phase, direction, distance , duration , fingerCount, pinchZoom) {
	          console.log("Distance pinched "+distance+" , Direction " + direction);
	        },
	        preventDefaultEvents: false
    	});

**Comment by mattbryson** [comment]
ok, ill have a look (and test it this time :) )

**Comment by Joshua-Interspace** [comment]
thank you so much, :)

**Comment by mattbryson** [comment]
This is a bit of a tricky one, i've added that property into to master, but as soon as the native functionality takes over, the library no longer gets the event, so it can no longer report on the swipe or pinch.

So its kinda useless....

**Comment by Joshua-Interspace** [comment]
well, i tried the latest build and now it logs both direction and distance AND still lets the pinch zoom happen, its just as i needed, :)

**Comment by Joshua-Interspace** [comment]
Oh, one more thing tho, how come when pinch zooming in it seem to report the distance accurate and while zooming out it also seems accurate until i hit max zoom out, then it reports +100 pixels for each tiny pinch out while the page dont zoom at all.

**Comment by mattbryson** [comment]
What do you mean by Max zoom out?
On 3 Feb 2015 06:33, "Joshua-Interspace" <notifications@github.com> wrote:

Oh, one more thing tho, how come when pinch zooming in it seem to report
the distance accurate and while zooming out it also seems accurate until i
hit max zoom out, then it reports +100 pixels for each tiny pinch out while
the page dont zoom at all.

—
Reply to this email directly or view it on GitHub
<https://github.com/mattbryson/TouchSwipe-Jquery-Plugin/issues/214#issuecomment-72601546>
.

**Comment by Joshua-Interspace** [comment]
if you zoom in a bit and then zoom back out untill the page dont zoom any more, then you have zoomed out maximum possible, and at that point if you continue to zoom out it starts reporting hundreds of pixels in distance for each cm your fingers goes apart.

**Comment by mattbryson** [comment]
hmm, ok, ill check.   The issues with this are that you are moving and scaling the page that you are trying to calculate distance on.  In the IOS Sim, it doesn't actually report anything when pinching and bubbling the events - so its a bit of a tricky one this.

**Comment by Joshua-Interspace** [comment]
ah, havent tried it yet in safari on our iphone, so far iv been using: https://developer.chrome.com/devtools/docs/remote-debugging , and a google nexus 5, :)
