### ISSUE TITLE
tap, longtap,  and hold - fire only 1 event

### ISSUE THREAD

**Issue by okwei2000** [mattbryson/TouchSwipe-Jquery-Plugin#216]
Is there is a way to let it only fire 1 event instead of all of them? for example,

If I press an element longer than longTapThreshold, can I just get the hold event instead all of the longtap, tap events. 

I need to handle tap, longtap and hold differently, so when hold is fired, I dont want to have the other 2 fired. tried event.preventDefault(), but doesnt work on mobile devices - seems to work OK on PC.

**Comment by marcussaad** [comment]
@okwei2000 ,

you could do something like this

```
$("your-selector").swipe({
        hold:function(event, target) {
            //do something interesting
            navigator.vibrate(100);
            event.preventDefault();
        },
       //how long does the user has to hold onto the element for the event to be triggered
        longTapThreshold:4000,
       //tap function. Make sure you prevent it. Do the same with other events (longtap).
        tap:function(event, target){
            event.preventDefault();
        }
    })
```
