### ISSUE TITLE
Reset swipeStatus event values?

### ISSUE THREAD

**Issue by justinputney** [mattbryson/TouchSwipe-Jquery-Plugin#217]
Is there a way to reset the event values of a swipeStatus?

If the user is swiping to the left, then changes the direction to swipe right (but doesn't cross the initial starting point) without picking up their finger, I'd like to reset the distance and the direction. Is this possible?

**Comment by mattbryson** [comment]
latest version will have currentDirection as well as direction in the event handlers.  currentDirection is the current movement, regardless of where the user started swiping.

**Comment by justinputney** [comment]
Awesome! That would be massively helpful. Thanks!

**Comment by mattbryson** [comment]
That's in now, let me know if it helps.

**Comment by justinputney** [comment]
Will do.

**Comment by justinputney** [comment]
Hi @mattbryson,
It's working great! Thanks!

The one issue I'm running into has to do with the triggerOnTouchLeave value (on a non-touch device). If you release outside of the target area, the swipe status continues to fire. Also it doesn't update the distances outside of the target area.

Those 2 glitches can be viewed on the swipe status example:
http://labs.rampinteractive.co.uk/touchSwipe/demos/Swipe_status.html

To replicate: 
1) click inside the test area
2) swipe outside
3) release
4) drag mouse back into the area

Event is still firing (although the distance value doesn't change once outside the area) and the event does not end until you click into the area.

Let me know if there's a workaround. It's more noticeable now that I'm able to change swipe directions on the fly.

Thanks!
