### ISSUE TITLE
Demo pages not working in Windows 8 / IE11

### ISSUE THREAD

**Issue by kevjvek** [mattbryson/TouchSwipe-Jquery-Plugin#218]
Matt, great plugin...been using for years. Many thanks!

That said...demo pages aren't working in IE11 on Windows touch laptop. I saw that you already fixed this for IE10. Everything works fine in other browsers tested (chrome 40, ff 35, safari 5.1.7). 

What is MS doing to gum up the works?

**Comment by fluffyhead** [comment]
I fixed swiping problems in IE11 with touchswipe the following way:
line 170
SUPPORTS_POINTER_IE10 = window.navigator.msPointerEnabled && !window.navigator.pointerEnabled && !SUPPORTS_TOUCH,

line 172
SUPPORTS_POINTER = (window.navigator.pointerEnabled || window.navigator.msPointerEnabled) && !SUPPORTS_TOUCH,

IE11 touch events otherwise are mapped to pointerdown etc. in line 410, which seems to be the cause for swiping problems in IE11. I also added this in my css code for swiping areas:
touch-action: pan-y;
-ms-touch-action: pan-y;
This way vertical scrolling is allowed, but horizontal swipes can be handled by touchswipe...

**Comment by mattbryson** [comment]
Yeah, not had time to fix it for MS pointer events yet.

**Comment by mikeschtiger** [comment]
I'll try that - thank you.

**Comment by Emnalyeriar** [comment]
@fluffyhead thanks man, this made it work for me on windows phone!

**Comment by rspahni** [comment]
+1 - awesome - Windows Phone works like a charm with this little fix

**Comment by mattbryson** [comment]
Ill get this ported in tested - anyone up for helping test it?

**Comment by rspahni** [comment]
What testing do you envisage on what devices producing what artifacts/evidence? Afraid I'm not experienced when it comes to testing JS on end-user devices... (I've got a WP8.1 Lumia 920 and a Win7 touch laptop but no Win8.1 touch PC).

**Comment by mattbryson** [comment]
Nothing particularly formal, but at the moment it doesn't swipe on some windows versions.  So it was more about getting a spread of devices used, as I only have a couple.  Once Ive ported it and tested it on my windows devices, I'll do a dev build with some notes for what to look out for.

But its basically, does it swipe or not!

**Comment by rspahni** [comment]
Alright Matt - so I’ll await your dev build then run it on all devices I can get my hands on.

 

Von: Matt Bryson [mailto:notifications@github.com] 
Gesendet: Mittwoch, 25. März 2015 11:44
An: mattbryson/TouchSwipe-Jquery-Plugin
Cc: rspahni
Betreff: Re: [TouchSwipe-Jquery-Plugin] Demo pages not working in Windows 8 / IE11 (#218)

 

Nothing particularly formal, but at the moment it doesn't swipe on some windows versions. So it was more about getting a spread of devices used, as I only have a couple. Once Ive ported it and tested it on my windows devices, I'll do a dev build with some notes for what to look out for.

But its basically, does it swipe or not!

**Comment by mattbryson** [comment]
Nice one - cant promise when, I have no free time at the moment!  hence the
lack of activity on TouchSwipe :(

**Comment by rspahni** [comment]
No worries - risk-taker that I am, I have moved @fluffyhead 's code to production already (no issues whatsoever so far, and at least WP8.1 swiping big time now). Good luck with your other endeavors in the meantime.

**Comment by flexphperia** [comment]
It's not working for me on WIN 8.1 + IE 11 + Lenovo Yoga. Swiping is not detected.

**Comment by freeaanzee** [comment]
Great fix, @fluffyhead!

**Comment by sunflowersh** [comment]
I downloaded 1.6.9, and swiping on Windows 8 IE11 is not working. I also tried @fluffyhead fix. Has anyone been able to make swipe work on the Windows phone using the version 1.6.9?

**Comment by MateEke** [comment]
@sunflowersh @fluffyhead 's fix is working for me on IE11 and Microsoft Edge on WP8.1 and WP10.
