### ISSUE TITLE
Cannot use doubleTap and pinchStatus together.

### ISSUE THREAD

**Issue by davidhooey** [mattbryson/TouchSwipe-Jquery-Plugin#219]
Not sure if I'm missing something or if this is a problem. Both will fire on their own, but only pinchStatus will fire when together.

```javascript
$("#theID").swipe({
    tap: function(event, target) {},
    doubleTap: function(event, target) {
        // Does not fire.
    },
    pinchStatus: function(event, phase, direction, distance, duration, fingerCount, pinchZoom) {
        // Does fire.
    },
    fingers: 2,
    pinchThreshold: 20
});
```

**Comment by mauliksoni110** [comment]
Facing the same issue, need a fix ASAP!

**Comment by mikeschtiger** [comment]
I think I found a bug in your touchSwipe. A doubleTap don't fire if a swipeEvent is defined an the same element. i think it's located in the function triggerHandler(event, phase) line 783. You put the tap handling in the else case. After correcting it, the double tap worked again in my page.

**Comment by mauliksoni110** [comment]
Can you please provide that changed code part here??

**Comment by mikeschtiger** [comment]
/**
* Trigger the relevant event handler
* The handlers are passed the original event, the element that was swiped, and in the case of the catch all handler, the direction that was swiped, "left", "right", "up", or "down"
* @param {object} event the original event object
* @param {string} phase the phase of the swipe (start, end cancel etc) {@link $.fn.swipe.phases}
* @inner
*/
function triggerHandler(event, phase) {
var ret = undefined;
//Swipes and pinches are not mutually exclusive - can happend at same time, so need to trigger 2 events potentially
if( (didSwipe() || hasSwipes()) || (didPinch() || hasPinches()) ) {
// SWIPE GESTURES
if(didSwipe() || hasSwipes()) { //hasSwipes as status needs to fire even if swipe is invalid
//Trigger the swipe events...
ret = triggerHandlerForGesture(event, phase, SWIPE);
}
// PINCH GESTURES (if the above didn't cancel)
if((didPinch() || hasPinches()) && ret!==false) {
//Trigger the pinch events...
ret = triggerHandlerForGesture(event, phase, PINCH);
}
} 
// CLICK / TAP (if the above didn't cancel)
if(didDoubleTap() && ret!==false) {
//Trigger the tap events...
ret = triggerHandlerForGesture(event, phase, DOUBLE_TAP);
}
// CLICK / TAP (if the above didn't cancel)
else if(didLongTap() && ret!==false) {
//Trigger the tap events...
ret = triggerHandlerForGesture(event, phase, LONG_TAP);
}
// CLICK / TAP (if the above didn't cancel)
else if(didTap() && ret!==false) {
//Trigger the tap event..
ret = triggerHandlerForGesture(event, phase, TAP);

}
// If we are cancelling the gesture, then manually trigger the reset handler
if (phase === PHASE_CANCEL) {
touchCancel(event);
}
// If we are ending the gesture, then manually trigger the reset handler IF all fingers are off
if(phase === PHASE_END) {
//If we support touch, then check that all fingers are off before we cancel
if (SUPPORTS_TOUCH) {
if(event.touches.length==0) {
touchCancel(event);
}
}
else {
touchCancel(event);
}
}
return ret;
}

**Comment by mauliksoni110** [comment]
Thanks! Will try this soon!

**Comment by mikeschtiger** [comment]
function triggerHandler(event, phase) {
var ret = undefined;
//Swipes and pinches are not mutually exclusive - can happend at same time, so need to trigger 2 events potentially
if( (didSwipe() || hasSwipes()) || (didPinch() || hasPinches()) ) {
// SWIPE GESTURES
if(didSwipe() || hasSwipes()) { //hasSwipes as status needs to fire even if swipe is invalid
//Trigger the swipe events...
ret = triggerHandlerForGesture(event, phase, SWIPE);
}
// PINCH GESTURES (if the above didn't cancel)
if((didPinch() || hasPinches()) && ret!==false) {
//Trigger the pinch events...
ret = triggerHandlerForGesture(event, phase, PINCH);
}
} 
// CLICK / TAP (if the above didn't cancel)
if(didDoubleTap() && ret!==false) {
//Trigger the tap events...
ret = triggerHandlerForGesture(event, phase, DOUBLE_TAP);
}
// CLICK / TAP (if the above didn't cancel)
else if(didLongTap() && ret!==false) {
//Trigger the tap events...
ret = triggerHandlerForGesture(event, phase, LONG_TAP);
}
// CLICK / TAP (if the above didn't cancel)
else if(didTap() && ret!==false) {
//Trigger the tap event..
ret = triggerHandlerForGesture(event, phase, TAP);

}
// If we are cancelling the gesture, then manually trigger the reset handler
if (phase === PHASE_CANCEL) {
touchCancel(event);
}
// If we are ending the gesture, then manually trigger the reset handler IF all fingers are off
if(phase === PHASE_END) {
//If we support touch, then check that all fingers are off before we cancel
if (SUPPORTS_TOUCH) {
if(event.touches.length==0) {
touchCancel(event);
}
}
else {
touchCancel(event);
}
}
return ret;
}

**Comment by mauliksoni110** [comment]
Thanks! Will try this soon!

**Comment by mattbryson** [comment]
Fixed in latest release
