### ISSUE TITLE
DoubleTap suddenly stopped working!

### ISSUE THREAD

**Issue by kingaki007** [mattbryson/TouchSwipe-Jquery-Plugin#220]
Here is the code. It used to work perfectly but now it suddenly stopped working.Tried giving doubleTapThreshold but still nothing works. All this images have anchor tags as well

<code>
 $('img', $obj).swipe({
                                                                     tap: function (ev, target) {
								            console.log('clicked ' + ev.type);
								        },
								        doubleTap: function (ev, target) {
								            alert('double clicked ' + ev.type);
								            AddToCollectionInMobile($(target));
								        },
								        longTap: function (ev, target) {
								            console.log('longHold ' + ev.type + " " + target);
								        },
								        longTapThreshold: 500,
								        fingers: 'all',
								        excludedElements: ""
								    });
</code>

**Comment by mikeschtiger** [comment]
I think I found a bug in the touchSwipe. A doubleTap don't fire if a swipeEvent is defined on the same element. i think it's located in the function triggerHandler(event, phase) line 783. The tap handling is put in the else case. After correcting it, the double tap worked again in my page.

**Comment by kingaki007** [comment]
I checked that earlier as well that is not the problem in my case. I am just wondering why did it suddenly stop working. It worked perfectly earlier even with swipeEvent and the problem you described wasn't same in my case. Anyways thanks others will benefit from that.

**Comment by mikeschtiger** [comment]
I can see in you that you use swipe AND doubleTab and longTab. 
Have you edit that jquery.touchSwipe.js? If not, the doubleTab/longTab will not fire.
