### ISSUE TITLE
Only 3 imgs appearing with Image Gallery Touchswipe

### ISSUE THREAD

**Issue by Waltz18** [mattbryson/TouchSwipe-Jquery-Plugin#227]
As the title says only 3 images are showing up even though I have 20+ in my code. 

http://www.everyhome.com/dir/sb.htm

I even changed var maxImages = 3 to maxImages = 10 and nothing. I'm hoping I messed up something small and someone could give some assistance on this issue. Thank you in advance. Other than this tiny issue i'm really enjoying using the plugin.

**Comment by lukatiks** [comment]
Your `#imgs` element is not nearly wide enough, with `1510px` it only fits 3 images `500px` wide. I think you should also remove whitespace between `<img>`s, or the vertical bar displayed between them will be getting in the way.
