### ISSUE TITLE
Not Working on <a> tags

### ISSUE THREAD

**Issue by alyeldegwy** [mattbryson/TouchSwipe-Jquery-Plugin#228]
i'm trying to use the plugin but it is not working on any <a> tag it there somthing i should do or it is a bug??

**Comment by symeonb** [comment]
by default the a tag is in the excludeElements just set 
excludedElements: ""
or a list of elements yoiu want to exclude.

**Comment by alyeldegwy** [comment]
Thanks 
Done and worked but the a tag is not clickable on mobile devices :) What to do??

**Comment by igorpetrov** [comment]
It isn't clear that some elements are disabled by default. I've spent about an hour trying to find what is going wrong...
