### ISSUE TITLE
Swipe not working on touch devices

### ISSUE THREAD

**Issue by Cedriking** [mattbryson/TouchSwipe-Jquery-Plugin#231]
Hello there, 
I'm currently making a game and I have a slider at the begining that explains how it works. I'm using TouchSwipe for this part as I need that on touch devices people are able to swipe to the next slide.

Everything is working fine on my computer, but as soon as I go to my Samsung galaxy s3 or an iPhone, it's not working.

I have a UL with many LI's in my html for the slider. and I only change classes on those LI's. Here is my javascript:

```javascript
$('.intro-slider-slides').swipe({
    swipe: function(e, d) {
      if (d === 'right') {
        return slider.goPrevious();
      } else if (d === 'left') {
        return slider.goNext();
      }
    }
  });
```

$('.intro-slider-slides') is the UL
I dont receive any kind of error/warning/message on the console so I'm stuck here, I dont know what it could be.

Thank you for your help.

**Comment by braianj** [comment]
so the solution was ....

**Comment by Cedriking** [comment]
Didn't used a slider after all :+1:

**Comment by braianj** [comment]
hehe
