### ISSUE TITLE
Cannot call unbind of null line 1574

### ISSUE THREAD

**Issue by irothenbaum** [mattbryson/TouchSwipe-Jquery-Plugin#237]
Version 1.6.6
When I call swipe("destroy") and immediately remove the element, I get a "cannot call unbind of null" at line 1574
https://github.com/mattbryson/TouchSwipe-Jquery-Plugin/blob/1.6.8/jquery.touchSwipe.js#L1574

For my own uses I applied a simple null check, but I don't know what the implications of that are so I haven't issued a pull request.

Let me know when a permanent solution is decided.

Many thanks!

**Comment by mattbryson** [comment]
Are you calling destroy from a swipe event? As in swipe left and then remove that item?

**Comment by irothenbaum** [comment]
Mine is not from a swipe event, but I notice that also creates a similar error (calling trigger of null). Here's an easy way to recreate.

```
$('body').swipe({
    tap:function(){
        $('body').swipe("destroy");
    }
});
```

The reason I'm destroying inside the event handler is because I was using Handlebars and it encouraged me to cleanup my Handlebar objects. So when I moved us to Touchswipe, I just ported that cleanup logic as well.

What are the drawbacks to removing an element without having first destroyed the swipe listener? If there are none, I might be inclined to remove that cleanup logic all together.

**Comment by mattbryson** [comment]
It's good practice, as if you remove the element from the DOM, and you have
events still bound to it, it prevents it from being garbage collected.

I'll have a look at making destroy work whilst events are still bound /
running, shouldn't be too hard.
