### ISSUE TITLE
Usage example causes error when used with jQuery 2.0.3 and jQueryMobile 1.4.2

### ISSUE THREAD

**Issue by mull01** [mattbryson/TouchSwipe-Jquery-Plugin#238]
I'm working on a project using jQuery 2.0.3 and jQueryMobile 1.4.2.
I'm using the usage example for testing.

When a swipe event is detect the following error is received:
![error](https://cloud.githubusercontent.com/assets/12733879/7964673/a66d61de-09de-11e5-8070-3ff82c689275.png)

Researching this I found comments in other sites that a wrapper function may correct the problem but I've been unable to achieve a fix.  

Does anyone know a possible work around for this?

**Comment by gpincheiraa** [comment]
I get the same error.

**Comment by mattbryson** [comment]
Closing as over a year old.  Please feel free to re open if you are still having issues.
