### ISSUE TITLE
"Lazy" vertical scroll registering as swipe

### ISSUE THREAD

**Issue by mxstrand** [mattbryson/TouchSwipe-Jquery-Plugin#241]
Hello - First, TouchSwipe is great solution - thank you.

When someone is holding a phone and scrolling upward with their thumb, their thump will usually drift to the left or right at the end of the scroll movement.  I might call this "lazy" scrolling.

Holding the phone with left hand, the thumb will drift left.  The right hand is opposite.

Even though the user intends this to be a vertical scrolling action, the distance their thumb covers horizontally is enough to register a left or right swipe.

I'm wondering if you can put a vertical distance option or check on the left/right swipes.  For example, if the starting and ending Y coordinate are greater than X pixels, the left/right swipe should not register.

I played with the allowPageScroll config but unfortunately that does not seem to resolve the issue.
Thank you for considering.

**Comment by afflicto** [comment]
I also need this.

**Comment by cmanza** [comment]
This really would be ideal.

**Comment by leptinella** [comment]
It's not vertical swipe distance though as the page scrolls so you don't swipe across the page vertically. One idea would be to measure the page's vertical scroll position at swipe start and end. If it's over a threshold then cancel the swipe.

**Comment by ncrcat** [comment]
I've the same issue, maybe it's possible to temporarily disable swipes if user is scrolling?

**Comment by ncrcat** [comment]
In case someone's interested, here's how I solved this issue:
Use swipeStatus "start" and "end" to control the page scroll position and set a flag "isScroll" as a result. The flag is then checked before handling swipes

`
$("element").swipe( {
      self: this,
      isScroll: false,
      startScrollPosition: 0,

      swipeStatus: function(event, phase) {
          var currentScrollPosition = $('body').scrollTop();

          switch (phase) {
              case "start":
                  self.startScrollPosition = currentScrollPosition;
                  self.isScroll = false;
                  break;

              case "end":
                  if (currentScrollPosition !== self.startScrollPosition) self.isScroll = true;
                  break;
          }
      },

      swipe:function(event, direction) {
        // Ignore event if it was recognised as scrolling
        if (self.isScroll) {
            return true;
        }

        switch (direction) {
            case 'right':
                // Handle RightSwipe
                break;

            case 'left':
                // Handle LeftSwipe
                break;

            case null:
                // handle Tap
                break;
        }
      },
      threshold:0,
      allowPageScroll: "vertical"
    });
`

**Comment by mattbryson** [comment]
threshold and direction values should have solved this.

Closing as over a year old.  Please feel free to re open if you are still having issues.
