### ISSUE TITLE
Prevent click event after swipe

### ISSUE THREAD

**Issue by symeonb** [mattbryson/TouchSwipe-Jquery-Plugin#246]
Hi - how can i prevent a click event firing after a swipe when using in a browser

here is a jsfiddle with an example  http://jsfiddle.net/0pmgwe0n/

Thanks
Symeon.

**Comment by teckel12** [comment]
First of all, you'll need to use v1.6.4 as newer versions broke the tap event when used along with swipe.  Also, you're jsfiddle doesn't include a click event so I modified your jsfiddle to make the swipe container an anchor object so a click event was fired.

Anyway...  The concept is to prevent the default click event, then trap taps with touchSwipe.  You can do this with anchor objects to allow the user to swipe for one action, or click for another, with only one or the other being triggered but never both.

Here's a jsfiddle example:
https://jsfiddle.net/jv5nnmb5/

**Comment by symeonb** [comment]
Thanks for the answer teckel - i have a better jsfiddle here http://jsfiddle.net/symeon/sbvvs4ab/  to demonstrate the problem.  This uses 1.6.4 and the tap does now work.  But the click event still fires after tap or swipe.  the solution I used was to set a flag when swiping and to not process the click i have just swiped , see this jsfiddle http://jsfiddle.net/symeon/quycddab/

**Comment by teckel12** [comment]
I think this is a much easier script that accomplishes the same thing:

http://jsfiddle.net/LhwfgL20/

**Comment by symeonb** [comment]
No it doesn't - i have amended it so that the click does an alert http://jsfiddle.net/symeon/LhwfgL20/1/     now when i swipe it does the swipe and then does the click.

I want it to click when i click on it, and not to click when i swipe on it.

**Comment by teckel12** [comment]
When I swipe on your jsfiddle I get a click event also.

Instead, just trap the tap event and use that as your click.  For example:

var link = $(this).attr('href');
if (link) window.location.href = link;

This would go inside the tap event and work like a click if the object was an anchor.  Or if not an anchor object, you could do whatever click event you wanted there.  For me, I'm using this as a carousel/slider where the slides may be clickable.  So, I want the ability to swipe the slides or click on it to go to a link.  The entire code is below:

		$(".home-slider .slide").swipe( {
			tap: function() {
				var link = $(this).attr('href');
				if (link) window.location.href = link;
			},
			swipeLeft: function() { homeSlide(-1); },
			swipeRight: function() { homeSlide(1); },
			excludedElements: ".noSwipe"
		});
		$(".home-slider .slide").click(function(event) {
			event.preventDefault();
		});

Seems like the simple, straight-forward solution.

**Comment by saturday1** [comment]
I modified this a bit, since the above script prevented my a-elements at all time.

```javascript
//Swipe functionality
jQuery(".sy-wrapper li").swipe( {
	tap: function() {
		var link = jQuery(this).attr('href');
		if (link) window.location.href = link;
	},
	swipeLeft: function(){
		jQuery(".sy-wrapper li a").click(function(event) {
			event.preventDefault();
		});
		thumbs.goToPrevSlide();
	},
	swipeRight: function(){
		jQuery(".sy-wrapper li a").click(function(event) {
			event.preventDefault();
		});
		thumbs.goToNextSlide();
	},
	excludedElements: ".noSwipe"
});
```

The problem is that this prevents all links after the first swipe. Do you know how to fix?

**Comment by mkamla** [comment]
@saturday1 you're calling the swipe function on a `li` element, so your `tap` function will fail since you're looking for an `href` attribute on a `li` element. You're `link` variable should instead look like the following:

```
tap: function(){
var link = jQuery(this).find('a').attr('href');
...
},
```

This may or may not clear up the issues you're seeing.

**Comment by saturday1** [comment]
Thanks @mkamla!. Totally missed that, and that did the trick! :)

**Comment by viniciusnz** [comment]
Fyi: I had the same issue here (using tap + swipe, the tap was always called even if in a vertical page  scroll on 1.6.15). I moved back to 1.6.4 and it solved the issue.

**Comment by saudisoftech** [comment]
can anyone please help me to solve this issue.

http://stackoverflow.com/questions/40818423/jquery-touchswipe-issue-with-link

**Comment by mattbryson** [comment]
@saudisoftech I saw you solved it for your implementation.  Its a tricky one this to solve for all, as the plugin needs to detect multiple phases of the the touch events (start, move, end) to then determine what to do, and the click is a combination of these (start and end).  It needs some detection in there that if the start and end fire within a certain threshold, and then distance between them is under a threshold, then trigger a click event rather than a swipe...
