### ISSUE TITLE
Swipe and longTap not working together on demo page

### ISSUE THREAD

**Issue by duncan-at-hiveit** [mattbryson/TouchSwipe-Jquery-Plugin#248]
Hi there,

I'm trying to test the Swipe vs Long Tap example at http://labs.rampinteractive.co.uk/touchSwipe/demos/Tap_vs_swipe.html.  Unfortunately, it doesn't seem to work on either my mobile device or PC's browser.  Only the swipe seems to work.

To verify, we downloaded 1.6.9 and created our own simple test and sure enough, they don't seem to work well together.  When "swipe" is removed, the longTap works fine.

Many thanks,
Duncan

**Comment by mattbryson** [comment]
fixed in 1.6.14
