### ISSUE TITLE
Tap events don't work in v1.6.8 along with swipe events.

### ISSUE THREAD

**Issue by teckel12** [mattbryson/TouchSwipe-Jquery-Plugin#250]
Using version 1.6.4, tap works great (click/swipe on the grey box):
http://jsfiddle.net/hLt6dybn/1/

Using version 1.6.8 the tap event never triggers:
http://jsfiddle.net/3qz40av4/1/

Via trial and error, I found that the tap event will trigger with 1.6.8, but if you're ONLY trapping tap events and not any swipe events.  The following is the same version 1.6.8 above, just with only tap and no swipe:
http://jsfiddle.net/uda2jchr/1/

(Note that I added the "threshold" variable but even removing it yields the same results.)

**Comment by evanart** [comment]
I'm having the same problem too. Tap events seem to be entirely broken in 1.6.8. In fact, I can't even get your last example to work (even with tap events only).

Even on the "Tap vs Swipe" page in the documentation, I can't get it to say "You tapped X times" by clicking/taping in the box.

http://labs.rampinteractive.co.uk/touchSwipe/demos/Tap_vs_swipe.html

Is there any workaround for this issue, aside from rolling back to 1.6.4?

**Comment by sierradog** [comment]
Same issue here. I rolled back to 1.6.4

**Comment by bsanth** [comment]
Hitting the same issue. Cannot move back to 1.6.4 as finger data is not available. Any solutions?

**Comment by mattbryson** [comment]
Should be sorted in the latest version.
