### ISSUE TITLE
TouchSwipe JS throws “ReferenceError: event is not defined” in Firefox

### ISSUE THREAD

**Issue by liranh85** [mattbryson/TouchSwipe-Jquery-Plugin#255]
Hi,

My project is using the TouchSwipe JS library as an image/video carousel solution. It's working pretty well, but has a serious problem in Firefox (latest version - 39.0): When swiping in any direction, it starts swiping, but when letting go it throws the error "ReferenceError: event is not defined". It appears that it is attempting to use the "touchend" event but fails for some reason.

Do you have any clue why this is happening and how to fix it?

Thanks!

**Comment by mattbryson** [comment]
Can't reproduce this - i'm looking at FF 42.0 OSX 10.10.5

If you can reproduce please re open with the OS and version and ill have  a look.

Cheers

m

**Comment by x-moe-x** [comment]
I have the same problem, using 1.6.6 at FF 45.5.0 Debian Jessie 64-bit
