### ISSUE TITLE
handler didn't recognize more than 2 fingers

### ISSUE THREAD

**Issue by rexcalibur** [mattbryson/TouchSwipe-Jquery-Plugin#259]
I wanted to use 4 fingers. Is this plugin limited only to 1 and 2 fingers? Even if the handler has this fingerCount attribute.

    $('#text').swipe( {
      swipe:function(event, direction, distance, duration, fingerCount, fingerData) {
         console.log('fingers + ' + fingerCount + ' direction = ' + direction);
      },
      threshold:0,
      fingers:'all'
    });

**Comment by YanLobat** [comment]
Maybe your device doesn't support multitouch

**Comment by rexcalibur** [comment]
hmmm, i am using samsung galaxy note and nexus 4.

**Comment by rexcalibur** [comment]
it always detected 2  fingers only. :(

**Comment by mattbryson** [comment]
This is hopefully fixed.  Added a demo for 3 finger swipes http://labs.rampinteractive.co.uk/touchSwipe/demos/Finger_swipe.html
