### ISSUE TITLE
pageX and pageY in event object is not work

### ISSUE THREAD

**Issue by yinhaibo** [mattbryson/TouchSwipe-Jquery-Plugin#263]
version:1.6.12
I found a bug in android device while using this plugin, and I try to fixed it.
(https://github.com/mattbryson/TouchSwipe-Jquery-Plugin/blob/master/jquery.touchSwipe.js#1053)
I found the event(a jQueryEvent object)'s pageX and pageY properties is not work(It will be 0 or a negative value) for some android device, It work well in safari and iOS, and I found the jQueryEvent has a touches array properties, and touchEvent object has a correct pageX and pageY value.

So, I make some change to my code, and I hope someone to fixed it professionally.
```
if (event.pageX <= 0 || event.pageY <= 0){
	var evt = event.touches ? event.touches[0] : event;
	if (evt != undefined){
		event = evt;
	}
}
```
I just to replace the event object using Touch event instead of jQueryEvent.

**Comment by mattbryson** [comment]
Where abouts are you adding this?  The event object is already normalised with `event.touches ? event.touches[0] : event`  before it checks the pageX and pageY, so not sue where its getting a 0 value...
