### ISSUE TITLE
Touch doesn't work on IE11(WP8.1) and Edge(Win10Mobile)

### ISSUE THREAD

**Issue by daniel-kukiela** [mattbryson/TouchSwipe-Jquery-Plugin#265]
Hi.
I found a problem and i think i can call it a bug :)

The code is detecting if browser supports touch and pointer. If touch is supported and an event occurs, it counts "touches" property to check the number of touch points. It is true for TouchEvent but not for PointerEvent, which does not have "touches" property.

It works on IE10 for Windows Phone 8, because IE10/WP8 doesn't support TouchEvents and touch points count check is bypassed (`return ((fingerCount === options.fingers || options.fingers === ALL_FINGERS) || !SUPPORTS_TOUCH);` in `validateFingers()` - `SUPPORTS_TOUCH` is false).
For the same reason it works on both desktop IE and Edge.

On IE11/WP8.1 and Edge/Win10Mobile TouchEvent is supported as well as PointerEvent, but PointerEvent is used (correctly) with finger count check ("touches" property of TouchEvent, which doesn't exist in PointEvent) because of SUPPORTS_TOUCH flag (incorrectly);

A quick fix for that would be:
Remove:
`SUPPORTS_TOUCH = 'ontouchstart' in window, //line 180`
Add:
`SUPPORTS_TOUCH = !SUPPORTS_POINTER && 'ontouchstart' in window,`
After:
`SUPPORTS_POINTER = window.navigator.pointerEnabled || window.navigator.msPointerEnabled,`

Keep in mind, that you can't simply use TouchEvent instead of PointEvent as it breaks the code for browsers on non touch devices.
PointerEvent occurs for any touch point (single finger, pen, mouse, touchpad). All of them have a type property, so for multitouch it is necessery to count events of touch type and use it instead of "touches" property of TouchEvent.

Regards,
Daniel

**Comment by mattbryson** [comment]
Sorry for the late reply on this, and thanks for the investigation into it!

Did you modify the plugin to get this working?  If so could you submit it as a PR and I can merge it in.

**Comment by mattbryson** [comment]
I have just merged some other PR's around windows touch support.  Try out the latest version ad see if that fixes the issues.

**Comment by filfat** [comment]
+1

**Comment by mattbryson** [comment]
Assuming the Windows phone merge solved this as heard nothing back.
