### ISSUE TITLE
Swipe vertical and horizontal

### ISSUE THREAD

**Issue by pedrocaseiro** [mattbryson/TouchSwipe-Jquery-Plugin#269]
Hey, I'm trying to enable vertical and horizontal swipping but had no good results so far. Anyone knows if it is possible? What i want to do is being able to swipe images left and right and at the same time if I want swipe up or down.

**Comment by mattbryson** [comment]
Hi, did you look at http://labs.rampinteractive.co.uk/touchSwipe/demos/Page_scrolling.html

A lot of the issues are caused by the browser page scrolling.  Do you need the page to scroll at all?  Or are you controlling this all with TS?

**Comment by pedrocaseiro** [comment]
Already solved it, thanks.
