### ISSUE TITLE
Increase speed of scroll on swipe

### ISSUE THREAD

**Issue by GitHubGreg** [mattbryson/TouchSwipe-Jquery-Plugin#270]
I have a WordPress theme (Photolux) which detects swipes and scrolls images horizontally as a result. Would anyone have a suggestion on how we could speed up the speed the images scroll horizontally when a swipe is detected?

**Comment by mattbryson** [comment]
Didn't even realise that it was in use in that theme!

The speed is not down to TS, all that does is detect a swipe, what happens after that is down to the WP theme.
