### ISSUE TITLE
Chrome pinch emulation does not register

### ISSUE THREAD

**Issue by Ciantic** [mattbryson/TouchSwipe-Jquery-Plugin#277]
1. Open this in Google Chrome: http://labs.rampinteractive.co.uk/touchSwipe/demos/Pinch_and_Swipe.html
2. Open dev tools (F12)
3. Toggle to device mode (Ctrl+shift+m)
4. Choose device, e.g. iPhone from dropdown, with touch emulation
5. Refresh the page
6. Use "Shift + Mouse Click & Drag", the cursor indicates pinch emulation by changing to different, but the demo does not register pinch gesture.

I'm not sure how Chrome pinch emulation is supposed to work, but it would be useful to get it working with the plugin to be able to test more easily.

**Comment by mattbryson** [comment]
Yeah, this is a chrome issue i'm afraid. 

i works in device simulators.
