### ISSUE TITLE
Detect MacBook touchpad events

### ISSUE THREAD

**Issue by sunyoureyes** [mattbryson/TouchSwipe-Jquery-Plugin#278]
Is it's possible to detect Apple MacBook touchpad events with this plugin?

Thanks.

**Comment by mattbryson** [comment]
Doesn't look like you can detect mac touch pad gestures in JS.    The only thing you can do is treat it like a scroll wheel event.  So, 2 fingers swipe up/down could trigger a scroll event - but this would be the same event if you used a mouse wheel etc, and would be different to a 2 finger swipe on an actual touch device-  so not sure how useful it would be.    Feel free to re open if you have any suggestions  or have come across a way of doing it.

m
