### ISSUE TITLE
delete please

### ISSUE THREAD

**Issue by romanlex** [mattbryson/TouchSwipe-Jquery-Plugin#282]
If I use swipe handler on my page, native ios vertical scroll not work properly.
I can't swipe page without viewport
How I can fix this?

**Comment by romanlex** [comment]
sorry, found solution( delete please

**Comment by monti84** [comment]
Can't you tell me please how you fixed the problem? I had to drop the plugin, because i was not find solution for this problem (vertical scroll & horizontal swipe).

Even these examples didnt work on iphone: http://labs.rampinteractive.co.uk/touchSwipe/demos/Page_scrolling.html

**Comment by mattbryson** [comment]
There are a few tickets related to this that I will get to at some point!
