### ISSUE TITLE
"fallbackToMouseEvents: false" has no effect in IE 10, 11 and Edge

### ISSUE THREAD

**Issue by benbrowning** [mattbryson/TouchSwipe-Jquery-Plugin#286]
It is not possible to select text on a page that is swipe-able on a laptop running IE10, 11 and Edge. Dragging the mouse results in a swipe even when fallbackToMouseEvents is set to false

The whole page is set to be swipe-able. I'd rather not set text elements to be excluded elements as there are lots of them on the page, which would make the swipe too difficult to achieve.

**Comment by mattbryson** [comment]
Yeah, this is a issue as IE uses pointer events which are hardware agnostic.  They fire for Mouse, Pen, Touch.

We need to check the 'pointerType' of the event and then we could honer the fallBackToMouseEvents on windows.


I've I do a build later today would you be able to help test it (I have no windows devices here)

**Comment by benbrowning** [comment]
Thanks Matt,
Sure thing, I can help test. Just let me know when there is something ready.

**Comment by mattbryson** [comment]
ive pushed a branch with it in:  pointer_event_type_detection, have a go and see what happens.

**Comment by benbrowning** [comment]
Hi Matt, tested it in Edge, IE11 and IE11 in IE10 rendering mode and it is fixed in all three.
Good job!

**Comment by mattbryson** [comment]
nice one, cheers for the testing.    Ill merge that in and push a release to npm.

m
