### ISSUE TITLE
Inputs disabled if in swipe area

### ISSUE THREAD

**Issue by ACTwebDesigns** [mattbryson/TouchSwipe-Jquery-Plugin#29]
Hi I was wondering if anyone else had this issue where I am unable to focus in on an input element if within swipe area?

**Comment by profluck** [comment]
$(".swipe-area").swipe({
    swipeStatus: function(event, phase, direction, distance, duration, fingers)
    {
      //  .. some code ...
    },
    excludedElements: "label, button, input, select, textarea"  // Here your list of excluded elements ...
});

**Comment by ZachBerman** [comment]
@mattbryson - Still encountering this issue, form inputs further down on page are disabled with use of touchswipe when called on 'body'...

**Comment by FourTran** [comment]
Hi @mattbryson ,
I wonder that is there anyway i can get element inside the swipe.
