### ISSUE TITLE
Minified / Combined - Issue

### ISSUE THREAD

**Issue by elbsurfer** [mattbryson/TouchSwipe-Jquery-Plugin#292]
Hello,
I use this plugin in my magento shop and selected to minify and combine JavaScript files, which results in the attached error. Does someone know how solve this issue?

Thanks.
![bildschirmfoto 2016-07-13 um 13 08 04](https://cloud.githubusercontent.com/assets/4470136/16801456/0ae117bc-48fb-11e6-8736-11003465a392.png)
![bildschirmfoto 2016-07-13 um 13 08 13](https://cloud.githubusercontent.com/assets/4470136/16801455/0adfd3a2-48fb-11e6-8785-ff2dcb7aa5b1.png)

**Comment by they-are** [comment]
Same here!

**Comment by mattbryson** [comment]
There is a minified version in the repo - which works ok.  what minification tool are you using?

**Comment by mattbryson** [comment]
Closing as over a year old.  Please feel free to re open if you are still having issues.
