### ISSUE TITLE
swipe with a little sliding

### ISSUE THREAD

**Issue by oelbaganwg** [mattbryson/TouchSwipe-Jquery-Plugin#295]
I'm using  swipe( { swipeStatus:swipe2, allowPageScroll:"vertical"} );

Is there any way to allow the div to slide a little as the user swipes?

**Comment by jwdinker** [comment]
You could do something like this....

$container.swipe({
            swipeStatus : function(event, phase, direction, distance, duration){
                
                    if(phase === 'move' && direction === 'left'){
                        $elementToTranslate.css({transform:'translateX(' + distance + 'px)'});
                        
                 .........

**Comment by mattbryson** [comment]
Closing as over a year old.  Please feel free to re open if you are still having issues.
