### ISSUE TITLE
IE8 swipe status firing once per iteration

### ISSUE THREAD

**Issue by michaelkaplan** [mattbryson/TouchSwipe-Jquery-Plugin#296]
Hi I'm not sure if this is something other people have ran into but when using the swipe status function I get the distance traveled and change the left of my element to move it back and forth. In IE8 the swipe status is only firing once and the distance captured at most is only 5px so I have to keep clicking and swiping to one side to move the element. Any idea why it won't continuously fire as long as I don't let go of my mouse? I tested in IE9 and it works perfectly. 

Thanks,
Michael

**Comment by Chinegoodman** [comment]
sorry,man.I am a new It-worker.And I did not use this plugin before.So I can not help U to solve this problem.So sorry.
Mybe,you can ask others solving this.

After all,Nice to see you! I am Chinese boy.

xiaopang



pangshifeng0539@126.com
 
From: michaelkaplan
Date: 2016-09-02 03:58
To: mattbryson/TouchSwipe-Jquery-Plugin
Subject: [mattbryson/TouchSwipe-Jquery-Plugin] IE8 swipe status firing once per iteration (#296)
Hi I'm not sure if this is something other people have ran into but when using the swipe status function I get the distance traveled and change the left of my element to move it back and forth. In IE8 the swipe status is only firing once and the distance captured at most is only 5px so I have to keep clicking and swiping to one side to move the element. Any idea why it won't continuously fire as long as I don't let go of my mouse? I tested in IE9 and it works perfectly. 
Thanks,
Michael

**Comment by michaelkaplan** [comment]
Any update on this Mark?

**Comment by mattbryson** [comment]
Closing as over a year old.  Please feel free to re open if you are still having issues.
