### ISSUE TITLE
swipe + tap + hold + scroll

### ISSUE THREAD

**Issue by alexey2baranov** [mattbryson/TouchSwipe-Jquery-Plugin#297]
Hello ! 

I need help. I wish to have window swipe left-right side and scroll vertically his content. And many children divs inside witch should be clickable (or maybe tappable) and long-tappable. And of course when user swipe window no click and tap event fired on children divs. And at the end of all window should 

This should works on desktops, android 4, 5, 6 and iPhones 5,6 . Is it possible? Thanks!
By now i can't configure plugin to get this behaviour

my configuration is

```
    $(window).swipe({

            swipeLeft: function (event, direction, distance, duration, fingerCount, fingerData) {
...
            },
            swipeRight: function (event, direction, distance, duration, fingerCount, fingerData) {
...
            },
            swipeStatus: function (event, phase, direction, distance, duration, fingers, fingerData, currentDirection) {
...
            },
            allowPageScroll: "auto"
        });

```

and this is for children divs:

```
        $(`#${this.io}`).click(function () {
...
            });

            $(`#${this.io}`).swipe({
                longTap: function (event, target) {

                },
                hold: function (event, target) {
...
                },
                threshold: 300
            });
```

This configuration has 2 errors.
1. iphones 5 (do not test on iPhone6) can not scroll window
2. desctop chrome throws #click# on children divs when swiping window

**Comment by Chinegoodman** [comment]
sorry,man.I am a new It-worker.And I did not use this plugin before.So I can not help U to solve this problem.So sorry.
Mybe,you can ask others solving this.

After all,Nice to see you! I am Chinese boy.



pangshifeng0539@126.com
 
From: alexey2baranov
Date: 2016-09-05 18:14
To: mattbryson/TouchSwipe-Jquery-Plugin
Subject: [mattbryson/TouchSwipe-Jquery-Plugin] swipe + tap + scroll (#297)
Hello ! 
I need help. I wish to have window swipe left-right side and scroll vertically his content. And many children divs inside witch should be clickable (or maybe tappable) and long-tappable. And of course when user swipe window no click and tap event fired on children divs. And at the end of all window should 
This should works on desktops, android 4, 5, 6 and iPhones 5,6 . Is it possible? Thanks!
By now i can't configure plugin to get this behaviour
my configuration is
    $(window).swipe({
            swipeLeft: function (event, direction, distance, duration, fingerCount, fingerData) {
...
            },
            swipeRight: function (event, direction, distance, duration, fingerCount, fingerData) {
...
            },
            swipeStatus: function (event, phase, direction, distance, duration, fingers, fingerData, currentDirection) {
...
            },
            allowPageScroll: "auto"
        });

and this is on children divs:
        $(`#${this.io}`).click(function () {
...
            });
            $(`#${this.io}`).swipe({
                longTap: function (event, target) {
                },
                hold: function (event, target) {
...
                },
                threshold: 300
            });

**Comment by thebanon** [comment]
It turns out touchSwipe.js doesn't handle "Hold" like finger.js "Press". Its okay, I believe in workarounds. Eventually, this can be natively adapted to TouchSwipe, but I prevent the tap event after hold by using

```
			hold:function(event, target) {
				var target = $(target),
                                      object = $("#swiper");
				object.swipe("disable");
				myfunction(a,b,c);
			},
```
To re-enable it use `object.swipe("enable");`Your CSS should control the layout of `object = $("#swiper");` and all of its children. This workaround is good for elements that use tap, doubletap, and hold.

**Comment by mattbryson** [comment]
Closing as over a year old.  Please feel free to re open if you are still having issues.
