### ISSUE TITLE
How can i use TouchSwipe with Jquery .on function ?

### ISSUE THREAD

**Issue by wackhope** [mattbryson/TouchSwipe-Jquery-Plugin#301]
Like
`$("body").on("swipe",".touch_area", {
  swipeStatus:function(event, phase, direction, distance)
  {
//codes
    },
    threshold:0
  });`

**Comment by teuzinPereira** [comment]
Hey, try to check issue number #281 .

**Comment by mattbryson** [comment]
I'm going to close this as Ill update the other ticket #281
