### ISSUE TITLE
Swipe is not working on Android devices

### ISSUE THREAD

**Issue by anahitaida** [mattbryson/TouchSwipe-Jquery-Plugin#310]
Hi,

I was testing the swipe on different devices. IOS works perfectly but on Android is buggy, not working generally.

Any idea? Plugin is not for all types of devices?

Thanks in advance.

**Comment by PierBover** [comment]
It's working fine in my phone with Marshmallow.

**Comment by mattbryson** [comment]
It is supported on Android, if you are still having the issue can you provide the exact android version / browser being used.

Closing as over a year old.  Please feel free to re open if you are still having issues.

**Comment by surajgd89** [comment]
Hi,

Swipe not working in mobile device
