### ISSUE TITLE
event.cancelable should be checked in touchEnd event handler

### ISSUE THREAD

**Issue by gidabyte** [mattbryson/TouchSwipe-Jquery-Plugin#311]
In the touchEnd event handler, there is this part:

```javascript
//call this on jq event so we are cross browser
if (options.preventDefaultEvents !== false) {
    jqEvent.preventDefault();
}
```

There should be an other check for jqEvent.cancelable, too, like this:

```javascript
//call this on jq event so we are cross browser
if (options.preventDefaultEvents !== false && jqEvent.cancelable !== false) {
    jqEvent.preventDefault();
}
```

Without this check, there are several warning messages thrown in Chrome (latest version).

**Comment by mattbryson** [comment]
Ah, great. Could you make a pull request? I'll merge it in...

**Comment by gidabyte** [comment]
Sure, I've just did a pull request: [https://github.com/mattbryson/TouchSwipe-Jquery-Plugin/pull/312](https://github.com/mattbryson/TouchSwipe-Jquery-Plugin/pull/312)

Thanks

**Comment by mattbryson** [comment]
Closing as already merged.  Cheers.
