### ISSUE TITLE
"TouchSwipe.js" and "Select2.js" conflict in Internet Explorer?

### ISSUE THREAD

**Issue by jinch** [mattbryson/TouchSwipe-Jquery-Plugin#313]
I found a conflict between "[TouchSwipe.js](https://github.com/mattbryson/TouchSwipe-Jquery-Plugin)" and "[Select2.js](https://select2.github.io/)" that breaks functionality in Internet Explorer. Apparently you can't include both plugins on one page without breaking the Select-2 drop downs. This only happens in Explorer, all other browsers are fine.

[**THIS EXAMPLE DEMONSTRATES THE ISSUE**](http://inchdesigns.com/projects/wtf/)

**_> Do you know what may be causing this and a possible work around to get these plugins to play nice in IE?_**

**Comment by jinch** [comment]
Resolved by adding the .select2 class to the exluded elements:
http://labs.rampinteractive.co.uk/touchSwipe/docs/tutorial-Excluded_children.html
i.e. (excludedElements:"label, button, input, select, textarea, .noSwipe, .select2")

**Comment by mattbryson** [comment]
Closing as over a year old.  Please feel free to re open if you are still having issues.
