### ISSUE TITLE
Can not run in the case of WIFI

### ISSUE THREAD

**Issue by FTutu** [mattbryson/TouchSwipe-Jquery-Plugin#317]
Android can run normally, apple under the condition of W - iFi can not run, but in the case of 4 g can run again

**Comment by mattbryson** [comment]
The connectivity has no bearing on the plugin.

Do the demos show the same issue?

http://labs.rampinteractive.co.uk/touchSwipe/demos/Basic_swipe.html

**Comment by mattbryson** [comment]
Closing as over a year old.  Please feel free to re open if you are still having issues.
