### ISSUE TITLE
Swipe Only Fires Once

### ISSUE THREAD

**Issue by samwisegrangee** [mattbryson/TouchSwipe-Jquery-Plugin#324]
I'm implementing TouchSwipe for an image slider here: https://madcap.wpengine.com/shop/apparel/third-coast-pocket-tee/

It worked fine when I sketched it out on Codepen: https://codepen.io/samwisegrangee/pen/QgoQqB

It even works on the mobile-simulator, but on a device my swiping only fires once.

**Comment by ollylove** [comment]
same here! sometimes it works, sometimes it doesn't and this is the warning in the console:

`[Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive.`

**Comment by mattbryson** [comment]
TouchSwipe does not mark any of the touch events as passive as they are not passive events.  It does need to block scrolling in some configurations.

So I don't think that error is coming from touchSwipe, or at least this branch of it.

Closing as over a year old.  Please feel free to re open if you are still having issues.
