### ISSUE TITLE
find the li under ul (swipe)

### ISSUE THREAD

**Issue by arunkp** [mattbryson/TouchSwipe-Jquery-Plugin#327]
I want to find the index of "li" when the swipeends on parent "ul", is it possible?
<img width="338" alt="screenshot 2017-08-17 13 13 04" src="https://user-images.githubusercontent.com/4560500/29408100-86ec4134-8364-11e7-9595-fcb00d96a319.png">

**Comment by mdss-single** [comment]
I think you can to add class to li and calculate index then

**Comment by mattbryson** [comment]
Closing as over a year old.  Please feel free to re open if you are still having issues.
