### ISSUE TITLE
not working with wordpress site

### ISSUE THREAD

**Issue by garethkusky** [mattbryson/TouchSwipe-Jquery-Plugin#328]
I have added jquery.touchSwipe.min.js and can see this is loaded when using browser developer tools. I have a simple div and the below code in an existing working plugin js file, but it doesn't appear to trigger - tested on Firefox and Android chrome browser

```
 $("#my-picks").swipe( {
    //Generic swipe handler for all directions
    swipe:function(event, direction, distance, duration, fingerCount, fingerData) {
      $(this).text("You swiped " + direction );  
    }
  });
```

I know for other js scripts $ needs to be changes to jQuery for WordPress. Is there something similar i need to do for this script?

Thanks

**Comment by dalenguyen** [comment]
It works on my WordPress site. It is really hard to test the behavior on the browser simulator, try it on your phone.

**Comment by ordin2342** [comment]
Wordpress with JQuery in no-conflict mode and 3rd party libraries can give you a headache, if you don't enqeue scripts properly. 

- Check out Wordpress Docs on how to enqeue scripts
- Use jQuery instead of $
- Make sure you're using document ready in you own code

Hope it helps.

**Comment by mattbryson** [comment]
closing as nearly a year old.  Please feel free to re open if you are still having issues.

**Comment by garethkusky** [comment]
How is this being closed as nearly a year old? I literally just bought the plugin and reported the issue
--
Sent from myMail for Android Monday, 17 September 2018, 00:00pm +01:00 from Matt Bryson  notifications@github.com :
