### ISSUE TITLE
Uncaught TypeError: Cannot read property 'ALL' of undefined

### ISSUE THREAD

**Issue by builderux** [mattbryson/TouchSwipe-Jquery-Plugin#330]
I am getting an error Uncaught TypeError: Cannot read property 'ALL' of undefined
This is my code http://prntscr.com/gtrb25

**Comment by mattbryson** [comment]
`jQuery.fn.swipe.fingers` is defined and used throughout the plugin, so it must be being cleared by some external code?

If you are still having the issue, please re open and proved an example that I can look at.
