### ISSUE TITLE
Three latest versions of the package are not present in npm repository

### ISSUE THREAD

**Issue by bIbI4k0** [mattbryson/TouchSwipe-Jquery-Plugin#332]
Last version on github - 1.6.18
Last version on npm - 1.6.15 ( https://www.npmjs.com/package/jquery-touchswipe )
Please, update npm repo. Thank you.

**Comment by SimonSchick** [comment]
Seconded, we are moving to webpack and this is a potential issue, can you please fix this?

**Comment by mattbryson** [comment]
yup, will have a look

**Comment by mattbryson** [comment]
should be sorted now
