### ISSUE TITLE
Warning with Chromium 

### ISSUE THREAD

**Issue by Tchoupinax** [mattbryson/TouchSwipe-Jquery-Plugin#336]
Hello, 
Your plugin works well but i have this issue using Chromium.
_Version 62.0.3202.75 (Official Build) Built on Ubuntu , running on LinuxMint 18.2 (64-bit)_

```
jquery.min.js:3 [Intervention] Unable to preventDefault inside passive event listener 
due to target being treated as passive. 
See https://www.chromestatus.com/features/5093566007214080
```
Regards,

**Comment by etetlow** [comment]
Hi, I have the same warning in Chrome Version 64.0.3282.167. Plugin works wonderfully though.
`[Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/5093566007214080`

**Comment by mattbryson** [comment]
Yes, this is a waring from Chrome that TouchSwipe hasn't flagged its swiping event listeners as `passive`.  However TouchSwipe is NOT passive, it does need to call `preventDefault` to stop page scrolling when swiping (if configured that way).  There is no way (that I can see) to flag the listener as {passive:false} and thus remove the warning in chrome.
