### ISSUE TITLE
allowPageScroll prevents native scrolling

### ISSUE THREAD

**Issue by ebatgerel** [mattbryson/TouchSwipe-Jquery-Plugin#337]
Hello guys i have a problem with pageScrolling
i have running on os 11 iphone 6
safari and google chrome not working
`allowPageScroll: "none",`
` triggerOnTouchEnd: false,`
 `maxTimeThreshold: 3000,`
` threshold: 75,`
 `preventDefaultEvents: false`

And its jumpy when i swipe left or right on IOS, but android is well.

And here is [video](https://drive.google.com/file/d/1_mTq8H2TVNIppRhdcCxW7UioJ3rojYBc/view)

**Comment by knoxcard** [comment]
This appears to lead to the solution.  A new pull request can fix this...also the browser has to be detected as Chrome to run the fix, other browsers wont recognize it.

https://stackoverflow.com/questions/37721782/what-are-passive-event-listeners

**Comment by mattbryson** [comment]
this is related to passive event listeners, but TouchSwipe does NEED active ones (as it does stop page scrolling so you can swipe).  Will be sorted in next release with a re worked event model.
