### ISSUE TITLE
Why tap event stopped working in Chrome Version 66.0.3359.139 ?

### ISSUE THREAD

**Issue by Inspirants-Vijay** [mattbryson/TouchSwipe-Jquery-Plugin#341]
I am using touchswipe.js plugin for products filters section.
You can also look the issue. Please check 
https://www.hatten.dk/produktListe.aspx?categoryid=815555600

It suddenly stopped working. In Eariler version, it was working fine.

Thanks
VJ

**Comment by mattbryson** [comment]
Hi VJ,

I have no idea where to look on your site for the issue.

I have tested the tap on the demo docs on latest chrome 69 (OSX) and it is working fine.

http://labs.rampinteractive.co.uk/touchSwipe/demos/Tap_vs_swipe.html

Closing for now, but feel free to re open if you are still seeing the issue.
