### ISSUE TITLE
Breaks HTML5 video and audio for touch devices when using mediaelement.js library.

### ISSUE THREAD

**Issue by krunkosaurus** [mattbryson/TouchSwipe-Jquery-Plugin#39]
Noticed when I switched from a less robust touch library to this one that it broke HTML5 video and audio touch event support for iOS devices when created via the mediaelement.js.

The play button overlay looks like this:

<div class="mejs-overlay-button"></div>

The actual play button on the lower left of the video that isn't clickable via iPad looks like this:

<div class="mejs-button mejs-playpause-button mejs-play"><button type="button" aria-controls="mep_1" title="Play/Pause"></button></div>

**Comment by anneeasterling** [comment]
Just a short note to say this thread -- and the ".noSwipe" class -- saved my sanity! I even went back and checked documentation to see if missed it there. So I might suggest added to your documentation on http://labs.rampinteractive.co.uk/touchSwipe/demos/index.html info on the magic of the ".noSwipe" class.

**Comment by mattbryson** [comment]
@anneeasterling it is in the section on excluding children from swiping.. http://labs.rampinteractive.co.uk/touchSwipe/demos/Excluded_children.html, but I suppose it could be made more obvious from the main index.
