### ISSUE TITLE
No swipe event fired when starting swipe upon a link element

### ISSUE THREAD

**Issue by alberto2000** [mattbryson/TouchSwipe-Jquery-Plugin#65]
On iPad iOS 6.2.1 when starting swipe over a link element it will highlight in gray iOS style and then the page will scroll. Subsequently, the allowPageScroll: 'none' directive will not work in such situations, too. Is this a known bug?

**Comment by malps13** [comment]
+1 Same issue here. It's particular problematic when you want to implement menu swiped from an edge of the screen and the links take most of the available space.

**Comment by mattbryson** [comment]
Have you allowed links to be swipe-able and implemented a tap event as above?

Thinking about it, I could out the box make a tap handler that triggers on any A tag automatically,  and then make A tags swipeable.. Likewise for inputs.....

**Comment by ciprianimike** [comment]
This works, swiping on a elements and tapping to open the link:
swipe: {
	onMouse: true,
	onTouch: true,
	options: {
		//exluded element list, less <a>
		excludedElements: "button, input, select, textarea, .noSwipe",
		//trigger <a> on tap
		tap: function(event, target) {
			$(target).parent().trigger('click');
		}
	}
}

**Comment by mablae** [comment]
@ciprianimike Nice snippet :+1:

**Comment by saudisoftech** [comment]
can anyone please help me to solve this issue.

http://stackoverflow.com/questions/40818423/jquery-touchswipe-issue-with-link

**Comment by rapt0p7** [comment]
@ciprianimike thanks, it works.
