### ISSUE TITLE
TouchSwipe clash with the click event

### ISSUE THREAD

**Issue by jingqian2013** [mattbryson/TouchSwipe-Jquery-Plugin#70]
if we have TouchSwipe ->swipe attached to the parent div and then having click event attached to the child element then the click event could never be triggered in ipad
for example:
script:

``` javascript
<script type="text/javascript">  
    $(document).ready(function(){     
      var paper = Raphael("canvas-zoom-map", 1025, 648);
      var circle2_back = paper.circle(258, 222, 20).attr({fill: "#7ac2e8", "stroke": "#7ac2e8"}); 
      circle2_back.click(function () {
         alert('111111111111111111111111111111111111122222222222');
         return false;
      });
      $(".ajax-simple-load-root").swipe({......some action here......});
    });
</script>
```

``` html
<div class="ajax-simple-load-root">
   <div id="canvas-zoom-map" style="margin: 0 auto; width: 1024px; height: 648px; ">
</div>
```

In this example, if we removed the  $(".ajax-simple-load-root").swipe then all click on the circle2_back triggered however, if we have $(".ajax-simple-load-root").swipe in doc ready then click on circle2_back could never triggered?
Plz help

**Comment by dan-leech** [comment]
I have it too. Swipe blocks clicks on inputs.
