### ISSUE TITLE
MSPointer events Windows 8 tablets

### ISSUE THREAD

**Issue by ZwaarContrast** [mattbryson/TouchSwipe-Jquery-Plugin#73]
Will there be support for Windows 8 tablet MSPointer events in the future?

**Comment by depiction** [comment]
Unfortunately, this is still an issue. I pulled up the basic touchSwipe demo page on a Lumia 920 and touchSwipe doesn't work. 

In my case, I'm using this with a jCarousel. I was able to add -ms-touch-action: none; to the carousel wrapper to make horizontal scrolling work, however users are no longer above to vertically scroll when swiping over the carousel.

**Comment by mattbryson** [comment]
Yeah, not had any time to look into the windows issues yet. Work has been far too busy....
