### ISSUE TITLE
Enabling and disabling scrolling on the fly.

### ISSUE THREAD

**Issue by joonaspaakko** [mattbryson/TouchSwipe-Jquery-Plugin#77]
I have a parent with child element inside. 
The child element can contain enough text for **vertical** scrollbars to appear.

``` html
<div id="parent">
    <div id="child">
         <!-- Lots of text -->
    </div>
</div>​
```

Initial setup:
- The child element is hidden.
- TouchSwipe is set to swipe in all directions ( To make discovering the ability to swipe as easy as possible ).
  - First swipe will show the child element ( swipeIN ).
  - Second swipe will hide the child element ( swipeOUT ).

**The problem** arises when the child element is shown and it has enough content to make scrollbars appear. You wont be able to scroll with a touch device, because swiping up or down will trigger swiping instead of scrolling.

So the plan was to disable swiping up and down _if_ scrollbars are present and child is visible, as demonstrated in the following image:
![TouchSwipe scroll](http://oi47.tinypic.com/104kyz4.jpg)

To get around this issue, I ended up digging into the plugins code to enable this behavior in a rather dirty way.

This is the idea behind what I did:

**First swipe ( swipeIN )**
If child has scrollbar, add class .forceScrolling

**Second swipe ( swipeOUT )**
Modified part in the TouchSwipe plugin would not trigger preventDefault() if the element has .forceScrolling class and the swipe is up or down.

**So**, I was thinking, maybe this could be implemented in the plugin in some way?

Something like:

``` javascript
var obj = $(this),
     objD = obj.data();

if ( 
    objD.scroll === 'vertical' && ( options.swipeLeft || options.swipeRight ) || 
    objD.scroll === 'horizontal' && ( options.swipeUp || options.swipeDown )
) {
    e.preventDefault();
}

```

This way you could just add new data to the element after a swipe.

``` javascript
$(this).data({ "scroll": vertical });
```

What say you?
Maybe I should just fork...

**Comment by juliandormon** [comment]
Hey Matt,
I was hoping you could help with me with a problem. I have noticed that the native pinch zoom feature in mobile Safari (8.1) ceases to work when allowPageScroll = none is set.

I am trying to disable vertical scrolling but allow pinch zooming, but it appears that changing the allowScrolling feature on the fly to auto will not allow the pinch zoom to work.

Here is my code:

...
$("#mediaOverlayContainer").css({ 'position': 'absolute', 'height': newH + 'px', 'top':                 $(window).scrollTop() + 'px' }).fadeIn().swipe({
            //allowPageScroll: "auto",

            pinchStatus: function (event, phase, direction, distance, duration, fingerCount, pinchZoom) {

                var scroll = $(this).swipe('option', 'allowPageScroll');

                console.log("Pinch zoom scale " + pinchZoom + ", Distance pinched " + distance + ", Direction " + direction + ", scroll: " + scroll);
                            
                //if (distance == 0) {
                //    $(this).swipe('option', 'allowPageScroll', 'none');
                //} else {
                //    $(this).swipe('option', 'allowPageScroll', 'auto');
                //}

            }
        });
...

**Comment by mablae** [comment]
@juliandormon Please create as a new Issue...

**Comment by malipetek** [comment]
@mattbryson nice solution but it enables for android chrome to swipe down to refresh feature which I dont want anywhere on page. I disabled it by:
>`body {
    touch-action: none;
}`
