### ISSUE TITLE
Windows 8 - Chrome 26 and Firefox 19

### ISSUE THREAD

**Issue by davidMGS** [mattbryson/TouchSwipe-Jquery-Plugin#83]
The demo pages do not work with Chrome 26 and Firefox 19 in Windows 8 64 bit pro.  It does work in IE10 surprisingly.

**Comment by kevjvek** [comment]
Hmmm...demo pages aren't working in IE11 on Windows touch laptop. Works fine in other browsers tested (chrome 40, ff 35, safari 5.1.7). What is MS doing to gum up the works?
